"""empty message

Revision ID: 13551a7698aa
Revises: 3ab3f07228f5
Create Date: 2021-10-23 16:54:51.726151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13551a7698aa'
down_revision = '3ab3f07228f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('Shows_id', sa.Integer(), nullable=False),
    sa.Column('Artist_id', sa.Integer(), nullable=True),
    sa.Column('Venue_id', sa.Integer(), nullable=True),
    sa.Column('Start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('Shows_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
