"""empty message

Revision ID: 93901b276674
Revises: 808b3d548c7a
Create Date: 2021-09-25 19:38:10.550048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93901b276674'
down_revision = '808b3d548c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'looking_for_talent_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_talent_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Artist', 'num_upcoming_shows')
    # ### end Alembic commands ###
